FROM python:3.7
COPY requirements.txt /

RUN pip install --upgrade pip
RUN pip install -r /requirements.txt
ENV TZ="America/Chicago"

RUN pip install gunicorn

COPY . /template
WORKDIR /template

RUN export PYTHONPATH=/app:$PYTHONPATH
RUN python setup.py install
